### ISSUE TITLE
Custom Resource per Flag Configuration

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/open-feature-operator#11]
Should a custom resource represent a single flag configuration or they be in a single config? I think it may make sense to have a resource per flag. Thoughts?

**Comment by AlexsJones** [comment]
A single custom resource per flag, how would that look?
```
apiVersion: v1
Kind: <Name>
spec: ???
```

I suppose a few challenges and thoughts spring to mind:

- How would be generate these new CRD dynamically and inject them into the API server?
- How would the CR themselves get named, would it be based off the flag key?
- If we had nested feature flags how does this represent as a Custom resource? 
- Scale: if we have a single Featureflag file of 10,000 flags and I need to express that in individual custom resources that's 10,000 unique etcd keys at least which will create an overhead on the cluster.
