### ISSUE TITLE
Stop the creation and mounting of the flagd-config config map in the case of kubernetes sync-provider

### ISSUE THREAD

**Issue by skyerus** [open-feature/open-feature-operator#117]
Previously `flagd` had no way of ingesting the `featureflagconfiguration` CRD directly so OFO created a config map and mounted it on the `flagd` sidecar.
Now `flagd` can use the `kubernetes` sync-provider, it's able to watch the `featureflagconfiguration` CRD directly. When the sync-provider is set as `kubernetes` the config map shouldn't be created and mounted to `flagd`.

**Comment by toddbaert** [comment]
I think we still want to support the ConfigMap based approach, particularly in cases when admins don't want to give permissions for flagd to hit the cluster API, so I think we want to make the creation of the ConfigMap conditional on the sync-provider, right?

If the sync-provider is `kubernetes` (the default) then we don't need to create the ConfigMap, but we might if it's `file`, yes?

It's possible I've missed something, but I still believe we support volume-mounted ConfigMaps via the `file` sync-provider.

**Comment by skyerus** [comment]
That's correct, thanks for pointing that out. I've amended the PR title and description to reflect this.
