### ISSUE TITLE
[Feature] [Question] What if a feature flag configuration does not exist?

### ISSUE THREAD

**Issue by thschue** [open-feature/open-feature-operator#16]
When creating a Pod with enabled but missing OpenFeatureConfiguration, the AdmissionWebHook denies the request:

```Error from server (FeatureFlagConfiguration not found): error when creating "STDIN": admission webhook "mpod.kb.io" denied the request: FeatureFlagConfiguration not found```

Although the feature flags might be necessary to run the application inside the pods, I'm unsure if such a configuration should avoid applying a manifest. I think the manifest should be applied, and as soon as the OpenFeatureConfiguration exists, it should be reconciled by the controller.

Therefore, I think it makes sense to inject the sidecar and create an empty configmap (if it doesn't exist) via the AdmissionController (Therefore, the pod will startup). In further consequence, the controller should add the Configuration to the ConfigMap. 

Nevertheless, we should write out an event if the OpenFeatureConfiguration does not exist.

WDYT?

**Comment by thschue** [comment]
I think this is very similar to #4

**Comment by AlexsJones** [comment]
![Untitled-2022-03-27-2101 excalidraw](https://user-images.githubusercontent.com/1235925/170997827-236ff2bc-cf4c-434b-ae79-8b4023cb2fae.png)

As discussed on a call, we will make sure there are an array of owner references that include the FF CR and the currently linked deployments/sts/ds

**Comment by thschue** [comment]
fixed with #18
