### ISSUE TITLE
ServiceAccount not found on pod admission [ Docker Desktop ] 

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/open-feature-operator#195]
## Repro:
1. Docker-desktop on M1 pro Mac
2. Create cert-manager installation
3. Install OFO `kubectl apply -f https://github.com/open-feature/open-feature-operator/releases/download/v0.2.16/release.yaml`
4. apply the example `kubectl apply -f config/samples/end-to-end.yaml`

```
│   Warning  FailedCreate  2s (x12 over 12s)  replicaset-controller  Error creating: pods "open-feature-demo-deployment-857 │
│ 6c7df67-" is forbidden: error looking up service account demo/open-feature-demo-sa: serviceaccount "open-feature-demo-sa" │
│  not found    
```

This issue looks to be around permissions/connectivity/naming the right service-account

**Comment by james-milligan** [comment]
Ive tested this with the latest release and it seems this bug has been resolved, are we happy to close this?

**Comment by beeme1mr** [comment]
Please reopen if the issue still persists with the latest version.

**Comment by L3o-pold** [comment]
Can we reopen this? We see similar issue on k8s v1.22.9. `Error creating: admission webhook "mutate.openfeature.dev" denied the request: ServiceAccount "default" not found`

**Comment by beeme1mr** [comment]
Hey @L3o-pold, could you please open a separate issue for this? Please also confirm that the service account controller is running in your environment. If it is running, please take a look at the log to see if it mentions anything about being unable to create the default account.

**Comment by L3o-pold** [comment]
@beeme1mr what's the service account controller?
