### ISSUE TITLE
[Feature] Improve reconcile function: only update configMaps on actual flag spec change

### ISSUE THREAD

**Issue by toddbaert** [open-feature/open-feature-operator#20]
Depends on https://github.com/open-feature/open-feature-operator/issues/3.

The updates can run on metadata changes and other reasons aside from the spec. It would be a nice improvement to only update the config maps when necessary.

@AlexsJones proposed maintaining a state in the status containing a hash of the flag definition. This seems like a good implementation.

**Comment by AlexsJones** [comment]
Possibly involves:
- sha on the FeatureFlagConfiguration of the configuration 
- annotation on deployments using the configuration added

**Comment by AlexsJones** [comment]
https://github.com/open-feature/open-feature-operator/pull/52

**Comment by beeme1mr** [comment]
Won't do
