### ISSUE TITLE
Implement end-to-end test

### ISSUE THREAD

**Issue by skyerus** [open-feature/open-feature-operator#205]
A kind cluster can be created via [a github action](https://github.com/marketplace/actions/kind-cluster).

Inject a simple lightweight workload that curls flagd to assert OFO is functioning as expected.

**Comment by toddbaert** [comment]
This is sorely needed.

**Comment by beeme1mr** [comment]
It looks like Helm also has a testing action. It may be useful for Helm based E2E tests.

https://github.com/marketplace/actions/helm-chart-testing
