### ISSUE TITLE
[Bug] Helm releases are not persisting during creation as part of the release process

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/open-feature-operator#219]
We need to save the chart created as part of the release process in `charts`

**Comment by beeme1mr** [comment]
I think we may want to consider using the [Helm Release Action](https://helm.sh/docs/howto/chart_releaser_action/) here. Basically, the charts will be published to the `gh-pages` branch and we would just expose that branch as our GitHub page.

This would have the following benefits:

- Avoid branch protection issues that are difficult to workaround.
- Remove charts from the main branch
- Follow a documented Helm deployment pattern

**Comment by AlexsJones** [comment]
Would it being on that branch still make the artefacts available?

**Comment by beeme1mr** [comment]
From what I can tell, yes. As long as the GitHub page contains the artifact, everything should work.

**Comment by AlexsJones** [comment]
Is this still open?

**Comment by beeme1mr** [comment]
Yes, it's still an issue. @skyerus was going to look into this tomorrow.

**Comment by skyerus** [comment]
I don't think [Helm release action](https://helm.sh/docs/howto/chart_releaser_action/) is exactly what we're looking for here as it creates a new release which we already have a workflow for (release-please). However, we can hijack the rest of the process and reproduce it in the existing release workflow.

- [ ] Create a branch called `gh-pages` from `main`
- [ ] Change the Github Pages branch setting to `gh-pages` [here](https://github.com/open-feature/open-feature-operator/settings/pages)
- [ ] Create a PR removing the existing published charts from `main`
- [ ] Create a PR merging `main` to `gh-pages` and re-adding the existing published charts
- [ ] Create a PR to `main` appending `release charts` to the existing workflow
