### ISSUE TITLE
Large FeatureFlagConfiguration custom resource will hit the K8s annotation limit

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/open-feature-operator#223]
As reported by a user

```
If the CRD contains ~2000 flags (I tried it with boolean values) you will reach a K8s limit, but I doubt if this would really a blocker cause if you have so many feature flags you've got another problem :wink: -  The FeatureFlagConfiguration "end-to-end" is invalid: metadata.annotations: Too long: must have at most 262144 bytes .
```

This can be circumvented in a few ways but collecting here for posterity.

**Comment by beeme1mr** [comment]
The limitation is imposed by Kubernetes itself and can be addressed by splitting the configuration across multiple CRs. Including a section on the issue and a workaround should be sufficient.

**Comment by thisthat** [comment]
To remediate the problem, we could document to use `--server-side` when applying Flag CRD. This way, the `kubectl.kubernetes.io/last-applied-configuration` annotation is not filled with the exact content of the CRD.

**Comment by beeme1mr** [comment]
@thisthat provided a workaround for large CRs.
