### ISSUE TITLE
Multiple custom resource links to deployments

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/open-feature-operator#224]
User report

> It would be great If you can assign multiple featureflag configurations to a deployment like [openfeature.dev/featureflagconfiguration](http://openfeature.dev/featureflagconfiguration): firstconfig, secondconfig

Needs evaluation on whether we would want to do this.

**Comment by beeme1mr** [comment]
Relates to https://github.com/open-feature/open-feature-operator/issues/17
