### ISSUE TITLE
Artifact Hub Improvements

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/open-feature-operator#231]
## Overview

Artifact Hub is an open source project for finding, installing and publishing Kubernetes packages. The OpenFeature Operator (OFO) is available on Artifact Hub but the configuration is basic. Improvements should be made to increase its discoverability.

## Requirements

- Searching for "openfeature" or "open feature" should return the OFO
- A readme should be included on the [landing page](https://artifacthub.io/packages/helm/open-feature-operator/ofo)
- A change log to should included
- The OpenFeature logo should be used
- A "verified publish" badge should be added
- An "official" badge should be added (if possible)

## Resources

 - https://artifacthub.io/docs/topics/repositories/helm-charts/
 - https://artifacthub.io/docs/topics/annotations/helm/

**Comment by james-milligan** [comment]
@beeme1mr  This requires an account to be setup for the OpenFeature org on Artefact Hub, otherwise there will be an association with a personal account (this is the current state)
