### ISSUE TITLE
(Mostly) invalid annotation: `openfeature.dev`

### ISSUE THREAD

**Issue by sftim** [open-feature/open-feature-operator#255]
The annotation key `openfeature.dev` is not valid. Public annotation keys should follow a convention:
```
rfc1123-dns-domain-name slash *pchar
```
For example: `my.domain.example/some-annotation-key`
A cluster operator can use private annotation keys, which contain no slash. For example: `some-annotation-key`. Software that's published for use across many clusters should not use private label keys or private annotation keys.

To fix this issue, OpenFeature operator should define a new key for enabling the controller's behavior, and deprecate the old `openfeature.dev` key. It's OK to continue to accept the old key indefinitely.

After the old annotation key has been deprecated for a while, and for extra credit, the admission control mechanism can send a [Warning:](https://kubernetes.io/blog/2020/09/03/warnings/) for any Pod, etc, that is still using the deprecated annotation key.

**Comment by james-milligan** [comment]
The `openfeature.dev: enabled` annotation could be refactored to something along the lines of `openfeature.dev/enabled: enabled` (open to suggestions for a better key as I'm not a fan of this one) to match the convention, however, it may be worthwhile removing this annotation all together. Within the web hook this annotation is is used for an early return in the `Handle` method:
```
	val, ok := pod.GetAnnotations()["openfeature.dev"]
	if ok {
		if val != "enabled" {
			m.Log.V(2).Info("openfeature.dev Annotation is not enabled")
			return admission.Allowed("openfeature is disabled")
		}
	}
```
The parsing of the `openfeature.dev/featureflagconfiguration` annotation then follows a very similar pattern, so we can simply just move the `openfeature.dev Annotation is not enabled` log line into the second annotation check:
```
	val, ok = pod.GetAnnotations()["openfeature.dev/featureflagconfiguration"]
	if !ok {
		return admission.Allowed("FeatureFlagConfiguration not found")
	}
	ffNames := strings.Split(val, ", ")
```
We can then provide a warning for the use of the deprecated  `openfeature.dev` annotation

CC: @AlexsJones @sftim @skyerus @beeme1mr @toddbaert

**Comment by sftim** [comment]
If keeping it, I'd go for `openfeature.dev/enabled: "true"`. That does mean quoting the string value in YAML; however, that's what is common for other boolean annotations.

I think it'd be useful to support having `openfeature.dev/enabled` set to either `"true"` or `"false"`. For special cases. For normal use, also allow people to omit it and have the OpenFeature controller infer things from `openfeature.dev/featureflagconfiguration`.

**Comment by james-milligan** [comment]
@sftim I'm unable to request you as a reviewer, however I've linked the issue to the PR I've opened, would appreciate your feedback.

**Comment by AlexsJones** [comment]
> The `openfeature.dev: enabled` annotation could be refactored to something along the lines of `openfeature.dev/enabled: enabled` (open to suggestions for a better key as I'm not a fan of this one) to match the convention, however, it may be worthwhile removing this annotation all together. Within the web hook this annotation is is used for an early return in the `Handle` method:
> 
> ```
> 	val, ok := pod.GetAnnotations()["openfeature.dev"]
> 	if ok {
> 		if val != "enabled" {
> 			m.Log.V(2).Info("openfeature.dev Annotation is not enabled")
> 			return admission.Allowed("openfeature is disabled")
> 		}
> 	}
> ```
> 
> The parsing of the `openfeature.dev/featureflagconfiguration` annotation then follows a very similar pattern, so we can simply just move the `openfeature.dev Annotation is not enabled` log line into the second annotation check:
> 
> ```
> 	val, ok = pod.GetAnnotations()["openfeature.dev/featureflagconfiguration"]
> 	if !ok {
> 		return admission.Allowed("FeatureFlagConfiguration not found")
> 	}
> 	ffNames := strings.Split(val, ", ")
> ```
> 
> We can then provide a warning for the use of the deprecated `openfeature.dev` annotation
> 
> CC: @AlexsJones @sftim @skyerus @beeme1mr @toddbaert

 `openfeature.dev/enabled: enabled` 

I don't think that looks very nice can we use  `openfeature.dev/enabled: true` ?

**Comment by james-milligan** [comment]
> I don't think that looks very nice can we use `openfeature.dev/enabled: true` ?

This approach is taken in this PR https://github.com/open-feature/open-feature-operator/pull/262
