### ISSUE TITLE
Add Helm config options

### ISSUE THREAD

**Issue by james-milligan** [open-feature/open-feature-operator#271]
The existing OFO helm chart customise overlay can be expanded to include environment variables for the operator to overwrite the default values for the following fields:

- sidecar metrics port
- sidecar exposed port
- sidecar evaluator (may be specific to flagd)
- sidecar image 
- sidecar version tag 

These environment variables would overwrite the existing internal defaults that are bing used by the operator, preventing the need for repeated configuration in the `FeatureFlagConfiguration` `FlagdSpec` property  (`8014`,`8013`, `json`...).

kustomize's `patchesStrategicMerge` can be used to append to the existing environment variable array, allowing these values to be overwritten through the `values.yaml` file, or through the cli: 
```
helm upgrade -i openfeature openfeature/open-feature-operator --set sidecar-image=my-custom-flag-source --set evaluator=yaml
```

**Comment by beeme1mr** [comment]
OFO is now fully configurable via Helm
