### ISSUE TITLE
Decouple feature flag spec from flagd config

### ISSUE THREAD

**Issue by james-milligan** [open-feature/open-feature-operator#274]
## Objective

The `FeatureFlagConfiguration` CRD currently contains flagd specific configurations. This can introduce challenges when a configuration only applies to a subset of workloads that have specific configuration requirements. Decoupling the flagd configuration from the feature flag spec allows for greater flexibility when managing OFO.

## Requirements

- [ ] Create a separate CRD for the `FlagSourceConfiguration`
- [ ] Deprecate the `flagDSpec` property from the `FeatureFlagConfiguration` CRD
- [ ] Add new annotation `openfeature.dev/flagsourceconfiguration`
- [ ] Multiple `FlagSourceConfiguration`s can be applied and merged.
- [ ] Add documentation `FlagSourceConfiguration` and how it's used.
- [ ] Remove requirement for [openfeature.dev/featureflagconfiguration](http://openfeature.dev/featureflagconfiguration) annotation to be present for sidecar injection.

## Question

- What do we want to call the new CRD?
- What does the migration progress look like?

**Comment by james-milligan** [comment]
duplicate of https://github.com/open-feature/open-feature-operator/issues/270

**Comment by AlexsJones** [comment]
Just to help clarify this; can we crystalise the use-case here?

What would be an example of say deployment A & B who are both using the same featureflagConifguration but different options in flagD? https/grpc and different ports perhaps ? 

_Something like that feels reasonable to me, but I want to understand the thinking on the following_

If so, how would we anticipate them selecting differentiated flagDconfigurations? Would we then have to annotate each deployment?
```
deploymentA -> flagDConfigA
deploymentB -> flagDConfigB
```
What happens if the config doesn't exist or is updated? 
Are we going to now watch the flagD config from flagD?

If we introduce a new provider e.g. `flagD2` or an updated provider in a cluster with v1 providers, how would they coexist, would there be a new CR for each provider?

**Comment by james-milligan** [comment]
> Just to help clarify this; can we crystalise the use-case here?
> 
> What would be an example of say deployment A & B who are both using the same featureflagConifguration but different options in flagD? https/grpc and different ports perhaps ?
> 
> _Something like that feels reasonable to me, but I want to understand the thinking on the following_
> 
> If so, how would we anticipate them selecting differentiated flagDconfigurations? Would we then have to annotate each deployment?
> 
> ```
> deploymentA -> flagDConfigA
> deploymentB -> flagDConfigB
> ```
> 
> What happens if the config doesn't exist or is updated? Are we going to now watch the flagD config from flagD?
> 
> If we introduce a new provider e.g. `flagD2` or an updated provider in a cluster with v1 providers, how would they coexist, would there be a new CR for each provider?

The flagDconfigurations exist as a separate resource (currently called `FlagdConfigurations`), and have their own separate annotations `openfeature.dev/flagdconfiguration`. Keeping them separate will allow for the example above to be possible.

The current behaviour is to return `allowed: false` if the configuration doesn't exist (as these configurations will be paired in the workload pod, and will likely be in error as a result)

If we further develop the provider we can introduce a new API version to accommodate the changes and a conversion function to maintain compatibility

**Comment by AlexsJones** [comment]
Thanks for expanding, what is the requested use case here, is it for different ports on the sidecar?

**Comment by james-milligan** [comment]
Full configuration of the injected container; `port`, `metricsPort`, `evaluator`, `image`, `tag`. We can currently handle most of these through the env field of `flagDSpec`, excluding the `image` + `tag`, but the introduction of a separation of interest will allow for the provider configurations to grow without bloating the `FeatureFlagConfiguration` and prevent eventual confusion with merging patterns in organisations with multiple configurations / combinations of configurations.
