### ISSUE TITLE
Kubernetes event handling exhibits inconsistent behaviour when multiple sync providers are configured

### ISSUE THREAD

**Issue by skyerus** [open-feature/open-feature-operator#324]
While expanding the e2e test suite to cover https://github.com/open-feature/open-feature-operator/issues/319 I discovered that configuring multiple sync providers causes unexpected behaviour in the kubernetes event listener. `flagd`'s internal state is not being updated to reflect a change in the FeatureFlagConfiguration.
To reproduce this:
1. Check out the branch in my PR.
2. Deploy the operator.
3. Run `kubectl -n open-feature-operator-system apply -f ./test/e2e/e2e.yml`
4. Expose the service `kubectl -n open-feature-operator-system port-forward service/open-feature-e2e-test-service 30000:30000`
5. Run the test (passes/fails intermittently) `./test/e2e/tests/002.crd-configuration-reconciliation.sh`

Tailing flagd's logs I can see that the event is received, the problem lies somewhere within https://github.com/open-feature/flagd/blob/main/pkg/sync/kubernetes/kubernetes_sync.go#L225

**Comment by toddbaert** [comment]
I think this was resolved with both these PRs:

https://github.com/open-feature/open-feature-operator/pull/326

https://github.com/open-feature/flagd/pull/339

(but we still need https://github.com/open-feature/open-feature-operator/pull/325 for tests)
