### ISSUE TITLE
[Logging] Customize flagd logger format

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/open-feature-operator#334]
## Overview

https://github.com/open-feature/flagd/pull/322 introduced customizable log formats. It also set the default format to console where previously it was set to JSON. The OFO should continue to default to JSON but expose the log format options to Helm and the flag source config CR.

## Requirements

- [ ] Add log format as an option in the flag source config CR
- [ ] Add a Helm configuration that set the default value cluster wide and default the value to json
- [ ] Update documentation in include information about the logger

**Comment by mowies** [comment]
Hey @beeme1mr !
I'd like to work on this :)

**Comment by mowies** [comment]
But i guess  the integration into the flag source config CR is not fully possible yet, since the controller behind it is not implemented yet right?
I can just add the field to the flag source config CRD for now 🤷🏼

**Comment by beeme1mr** [comment]
Hey @james-milligan, could you please answer @mowies question?

**Comment by james-milligan** [comment]
@mowies adding this configuration to the controller is relatively straightforward as we can pass this configuration to the sidecar via an environment variable.
You would just need to extend the `ToEnvVars` method in `/apis/core/v1alpha1/flagsourceconfiguration_types.go` to include the `FLAGD_LOG_FORMAT` env var following the pattern of the existing configurations

**Comment by mowies** [comment]
Ahh ok! I went straight for the `v1alpha2` API version and that file is basically empty :D

**Comment by james-milligan** [comment]
No problem, most / all of the logic is found in the `v1alpha1` package which we use as our hub, we then use conversion functions to convert all later versions to the hub version
