### ISSUE TITLE
Bundle Flagd Updates with Renovate

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/open-feature-operator#349]
Renovate automatically opens PRs when a new flagd version is available. Unfortunately, it's currently opening two separate PR per version.

Example:
	- https://github.com/open-feature/open-feature-operator/pull/343
	- https://github.com/open-feature/open-feature-operator/pull/342

This can likely be solved by properly [grouping](https://docs.renovatebot.com/noise-reduction/#package-grouping) the flagd helm-value update with the regex update.

**Comment by mowies** [comment]
I fixed this in #418. I think this issue can be closed as completed.
