### ISSUE TITLE
Issue with out-dated playground instructions

### ISSUE THREAD

**Issue by salaboy** [open-feature/open-feature-operator#367]
Hi folks.. 
the instructions here look out-dated: https://github.com/open-feature/open-feature-operator/blob/main/docs/getting_started.md

Can you please guide me on how to get the playground up and running with K8s? 

I am happy to send a PR if someone share some pointers

**Comment by beeme1mr** [comment]
Hi @salaboy, could you please describe what issue you're running into? I was able to run the demo in a new cluster. Did you install cert management and the OpenFeature Operator (OFO) before running `make deploy-demo`? The OFO install instructions can be found [here](https://github.com/open-feature/open-feature-operator/blob/main/docs/installation.md). There's also a blog post that walks through the [process end to end](https://docs.openfeature.dev/docs/tutorials/ofo).

Either way, it seems like there some usability issues with our getting started docs. Your feedback would be very much appreciated.

**Comment by salaboy** [comment]
@beeme1mr interesting.. I couldn't even run `make deploy-demo` because there is no `Makefile` in that repo. Do you have an old `Makefile`?  Or maybe I am missing something

**Comment by beeme1mr** [comment]
Ah, I see the issue. The `Makefile` is actually in [this repo](https://github.com/open-feature/open-feature-operator/blob/main/Makefile#L160). The reference to the demo application was included so you could see the source. I'll update the getting started section to make this more clear. Sorry about that!

FYI @toddbaert

**Comment by agardnerIT** [comment]
https://github.com/open-feature/killercoda/issues/6

**Comment by beeme1mr** [comment]
Resolved by: https://github.com/open-feature/open-feature-operator/pull/469
