### ISSUE TITLE
Move controllers into their own packages

### ISSUE THREAD

**Issue by bacherfl** [open-feature/open-feature-operator#393]
# Short abstract

Right now, all controllers (FeatureFlagConfigurationController, FlagSourceConfigurationController) are located in a common controller package. With this issue I would like to propose to move each of those controllers into their own package.

# Why 

In general, packages should be kept as small as possible to make them easy to understand. Also, in the ginkgo test suite, the controllers might interfere with each other when new tests are added. We recently observed that behaviour in https://github.com/keptn/lifecycle-toolkit, where the tests were failing randomly. Moving the controllers to their own packages will help to isolate them from each other when running the test suites

# Tasks

- [ ] Create a new package for each controller, i.e. `controllers/featureflagconfiguration/controller.go` and `controllers/flagsourceconfiguration/controller.go`
- [ ] Code that is shared between the existing controllers should be moved into a common package, e.g. `controllers/common/common.go`

**Comment by odubajDT** [comment]
I would like to take this ticket if possible :)

**Comment by toddbaert** [comment]
Assigned!
