### ISSUE TITLE
Create Unit tests for Controllers using K8s Fake Client

### ISSUE THREAD

**Issue by bacherfl** [open-feature/open-feature-operator#394]
# Short abstract

The goal of this issue is to add unit tests for the `FeatureFlagConfiguration` and `FlagSourceConfiguration` controllers, using the Kubernetes [fake client](https://pkg.go.dev/k8s.io/client-go/kubernetes/fake).

# Why 

Adding these tests will help to better verify the behavior of the controllers, as opposed to the ginkgo component tests, since with this approach it's possible to check for certain assertions after each invocation of the controller's `Reconcile` method, and controlling the current state of the relevant resources with the fake kubernetes client.

# Functional requirements

- [ ] Create unit tests using the K8s fake client for both controllers

**Comment by odubajDT** [comment]
Hi, I would like to work on this please :)

**Comment by toddbaert** [comment]
@odubajDT assigned!
