### ISSUE TITLE
[Feature] [Architecture] [Question] Finalization and deprovisioning

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/open-feature-operator#4]
When deleting a custom resource definition we need to decide whether that will delete the mounted configmaps or not.
It would have an impact on running workloads that could be mitigated by flagd caching in the last good spec in running memory.

Thoughts welcome.

**Comment by beeme1mr** [comment]
My initial thought is that we would want to delete the mounted configmap and remove the config from the `flagd` cache. I think my expectation as an OpenFeature user would be that a flag would be removed and the SDKs would simply return the default value.

**Comment by AlexsJones** [comment]
That makes sense - though I think we'd have to retain the agent otherwise force a completely new pod to be created. 
How about these steps...
1. when the CR is deleted it looks at all the pods in the status reference https://github.com/open-feature/open-feature-operator/issues/7
2. It will retain the configmap mounts but empty out the configmap itself `{}` which would avoid a complete pod reload

**Comment by thschue** [comment]
So, currently, I'm planning to implement it this way:

## Cases
* Cleaning up ConfigMaps when CR for FeatureFlagConfiguration exists
* Cleaning up ConfigMaps when CR for FeatureFlagConfiguration does not exist

## Assumptions
* In both cases, the resources consuming the configmap are added as owners. Therefore, we know which deployments are using it
* When the configmap has no owner(reference), it gets deleted in any way. Therefore we don't have to care about cleaning up when the featureflagconfiguration doesn't exist
* When a configmap does not exist, and a new pod is scheduled, it gets created

## Cleaning up ConfigMaps when CR exists
* We will also add the controller as an owner reference (for watching the ConfigMap)
* During reconciliation, the controller checks if the ConfigMap has only the controller as an owner. If this is the case, the configmap gets deleted

## Things to consider
* When the configmap gets deleted and reconciled afterward, we have to ensure that the pods which are consuming the configmap are re-added as owners (in the controller)
