### ISSUE TITLE
fix renovate configuration

### ISSUE THREAD

**Issue by james-milligan** [open-feature/open-feature-operator#415]
On flagd release renovate should open a PR to bump the current flagd version used by the operator, however `v0.4.5` has not caused a PR to open, this is likely due to the renovate configurations and the new flagd monorepo

https://github.com/open-feature/open-feature-operator/blob/613306011016a3cbb7fbc23a2273aecfd26a3bbf/apis/core/v1alpha1/flagsourceconfiguration_types.go#L50

**Comment by mowies** [comment]
I can work on this :)
