### ISSUE TITLE
Add debugLogging field to flagSourceConfiguration

### ISSUE THREAD

**Issue by james-milligan** [open-feature/open-feature-operator#416]
Add a bool field to the FlagSourceConfguration CRD to control the addition of the `--debug` flag to the injected sidecar

**Comment by toddbaert** [comment]
Good idea.

**Comment by odubajDT** [comment]
I would like to tackle this ticket

**Comment by odubajDT** [comment]
surely, thank you!

**Comment by odubajDT** [comment]
Insights from discussion between me and @toddbaert, afterwards also with @thisthat and @bacherfl  :

Adding this new field for flag enabling is an awesome idea. Additional to that, we discussed the possibility to also add an additional field for direct argument passing to the injected sidecar. 

We agreed that the best approach would be to have a list of "strong" flags (like `debugLogging`) which will have their place in the CRD spec and can be enabled/disabled via this parameter, but additionally introduce a `rawSidecarArgs` field for the flexibility of adding needed flags. This field can be very useful for development reasons/debugging or adding some advanced flags from the users.

We are open for any additional suggestions/concerns from the community!

**Comment by beeme1mr** [comment]
> introduce a `rawSidecarArgs` field

I think this is a good idea. 👍

**Comment by Kavindu-Dodan** [comment]
Just for my understanding, is the idea to use `rawSidecarArgs` to pass any random side-car (flagd) accepted flag ?

**Comment by odubajDT** [comment]
> Just for my understanding, is the idea to use `rawSidecarArgs` to pass any random side-car (flagd) accepted flag ?

Exactly, a good use case would be a need to debug some issues and enable advanced logging in flagD. Therefore there is no need to adapt the OF operator, the developer/user can pass these parameters via FlagSourceConfiguration. I think we use the same approach already with provider arguments in FlagSourceConfiguration CRD.
