### ISSUE TITLE
Discrepancy of OFO & flagd on file source naming  

### ISSUE THREAD

**Issue by Kavindu-Dodan** [open-feature/open-feature-operator#433]
Pre-requisites:

- [x] https://github.com/open-feature/open-feature-operator/issues/529
- [ ] https://github.com/open-feature/flagd/issues/983
- [ ] https://github.com/open-feature/open-feature-operator/issues/531

**Background**

flagd is capable of accepting file-based feature flag configurations. 

From flagd documentation, file-based configurations are accepted with URI or Source with `file` prefix [1] .

`flagd start --uri file:etc/featureflags.json` 

or sources yaml [2]
```
- uri: config/samples/example_flags.json
    provider: file
```

 In OFO however, `FlagSourceConfiguration` require the provider to be `filepath` [3]

```
  - source: /etc/flags.json
    provider: filepath
```

This mixed usage has the potential for confusion. 

**Improvement**

We should aim to unify this terminology, agreeing to a single name (similar to `http`, `grpc` and `kubernets`). Given that this is a breaking change, we could make this a part of beta version of the API with backward compatiblity. 

[1] - https://flagd.dev/reference/sync-configuration/
[2] - https://flagd.dev/reference/sync-configuration/#source-configuration
[3] - https://github.com/open-feature/open-feature-operator/blob/main/docs/flag_source_configuration.md#source-fields

**Comment by odubajDT** [comment]
This issue was resolved by https://github.com/open-feature/open-feature-operator/pull/535 in [this](https://github.com/open-feature/open-feature-operator/pull/535/files#diff-2be71624b02bf8c81b8480b76adb6eb84f949ef9307614a5c71a8939643c04e5R7) place
