### ISSUE TITLE
Introduce a Helm Documentation check in the pipeline

### ISSUE THREAD

**Issue by thisthat** [open-feature/open-feature-operator#449]
## Goal

Introduce a GH Workflow that verifies at each PR the documentation of the Helm chart is up2date. 

## Technical Details

The [Bitnami Readme Generator For Helm](https://github.com/bitnami-labs/readme-generator-for-helm) is a powerful tool that we could leverage to auto-generate the documentation for the Helm Charts. Furthermore, we can use it to enforce the documentation of the charts to be always up to date (see an [example in Keptn](https://github.com/keptn/lifecycle-toolkit/blob/main/.github/scripts/generate-helm-docs.sh)).
Furthermore, this avoids the need to handle huge markdown tables by hand. 

## Acceptance Criteria

- [ ] Introduce a workflow that is triggered when a change in the `chart` repo occurs at each PR
- [ ] If the documentation is not up2date, fail the workflow. 
- [ ] A handy script is available to re-generate the table

## DoD

- [ ] Documentation for Helm Chart is checked at each PR

**Comment by odubajDT** [comment]
Hello, I would like to take this issue :)
