### ISSUE TITLE
Auto update the readme on release

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/open-feature-operator#46]
Currently we update the semver of the latest release by hand after a release in the main README.md
It would be useful to automate this as part of the release process

**Comment by beeme1mr** [comment]
We can use release please for this. You can see an example of something similar in the [Node contrib repo](https://github.com/open-feature/node-sdk-contrib/blob/main/release-please-config.json#L12).

**Comment by skyerus** [comment]
Completed by https://github.com/open-feature/open-feature-operator/pull/80

**Comment by skyerus** [comment]
Reverted
Now using release please to achieve this behaviour: https://github.com/open-feature/open-feature-operator/pull/84
