### ISSUE TITLE
chore: refactor renovate.json to be more general

### ISSUE THREAD

**Issue by odubajDT** [open-feature/open-feature-operator#465]
It would be nice to refactor renovate.json to be more general when looking for files and dependencies that need to be updated. 

Instead of using regexes for each file we should implement a custom regex for a comment, that will be added to the places, where dependencies should be updated. In this case, whenever we add a new dependency, we do not need to add a new entry to renovate.json. There already is a general regex, so it would be nice to investigate if this one covers all scenarios and clean up the unneeded ones.

A nice example can be found here https://github.com/keptn/lifecycle-toolkit/blob/main/renovate.json

and the usage here https://github.com/keptn/lifecycle-toolkit/blob/main/Makefile#L3

**Comment by odubajDT** [comment]
I would like to work on this issue :)

**Comment by mowies** [comment]
I'd like to work on this!
