### ISSUE TITLE
documentation formatting is broken for crds

### ISSUE THREAD

**Issue by james-milligan** [open-feature/open-feature-operator#470]
some sections of the generated crd documentation are not being generated / formatted correctly, this can be seen here:
https://github.com/open-feature/open-feature-operator/blob/main/docs/crds.md#featureflagconfigurationspecflagdspecenvsindex
![Screenshot 2023-04-14 at 15 18 49](https://user-images.githubusercontent.com/75740990/232070440-83dc6fc0-f195-4fba-b79d-b7a26c5277ea.png)

**Comment by RealAnna** [comment]
I can take this one !
