### ISSUE TITLE
[DOCS] Docs improvements and possible bug

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/open-feature-operator#483]
I was going end-to-end as a new user would.

1. Start here: https://github.com/open-feature/open-feature-operator/blob/main/docs/installation.md
2. The above page should link at the bottom to: `https://github.com/open-feature/open-feature-operator/blob/main/docs/getting_started.md` (otherwise I've installed but can't use)
3. In my demo setup, I don't seem to need `FlagSourceConfiguration` so to avoid confusion, possibly move this elsewhere (or remove if it is legacy?)
4. [This code snippet](https://github.com/open-feature/open-feature-operator/blob/main/docs/getting_started.md#reference-the-deployed-flagsourceconfiguration-within-a-deployment-spec-annotation) references `openfeature.dev/flagsourceconfiguration` which I believe is a typo. Using this in my setup doesn't inject the sidecar. Instead I need to use `openfeature.dev/featureflagconfiguration`

**Comment by james-milligan** [comment]
Hi @agardnerIT, I looked through the getting started guide and looks like there was a versioning issue with the example crd which I've [fixed here](https://github.com/open-feature/open-feature-operator/pull/485). This does not resolve this issue however as it seems there is a wider docs issue.

Were you getting an error when deploying the `FlagSourceConfiguration`, it may be that the versioning issue fixed above was preventing the deployment of the resource, and as a result blocking pod deployment as the `FlagSourceConfiguration` defined in the `openfeature.dev/flagsourceconfiguration` could not be found, please let me know if this resolves the issue. 

>[This code snippet](https://github.com/open-feature/open-feature-operator/blob/main/docs/getting_started.md#reference-the-deployed-flagsourceconfiguration-within-a-deployment-spec-annotation) references openfeature.dev/flagsourceconfiguration which I believe is a typo. Using this in my setup doesn't inject the sidecar. Instead I need to use openfeature.dev/featureflagconfiguration

Using the `openfeature.dev/featureflagconfiguration` annotation is [deprecated](https://github.com/open-feature/open-feature-operator/blob/main/docs/annotations.md#openfeaturedevfeatureflagconfiguration). The configuration for the injected sidecar is defined using the `FlagSourceConfiguration` resource, which can reference a `FeatureFlagConfiguration` as one of its `Sources`, the docs for the `FeatureFlagConfiguration` spec can be found [here](https://github.com/open-feature/open-feature-operator/blob/main/docs/crds.md#flagsourceconfigurationspec).

```mermaid
flowchart TD
    A[Pod]-->|openfeature.dev/flagsourceconfiguration| B[FlagSourceConfiguration CR]--> |sources| C[FeatureFlagConfiguration]
    B[FlagSourceConfiguration CR]--> |sources| D[FeatureFlagConfiguration]
B[FlagSourceConfiguration CR]--> |sources| E[HTTP sync]
```

**Comment by Kavindu-Dodan** [comment]
Thank you @james-milligan  for the mermaid diagram. I added this to our documentation :) 

@agardnerIT  I think this PR fixed your concerns and documentation is now updated - https://github.com/open-feature/open-feature-operator/pull/496
