### ISSUE TITLE
Migrate to Go 1.18

### ISSUE THREAD

**Issue by toddbaert** [open-feature/open-feature-operator#49]
[Kubebuilder now supports Go 1.18](https://github.com/kubernetes-sigs/kubebuilder/releases/tag/v3.5.0). With this, it might be a good time to update both the operator and flagd to 1.18. I'm particularly excited for the possibility of using generics to greatly simplify flagd.

**Comment by przysiadZeSztanga** [comment]
simple change, remember to change go get to go install in Makefile. Done this in operator I work on, no issues spotted



btw, what I need to do to contribute? I cannot create branch

**Comment by AlexsJones** [comment]
The build tools have very purposefully been left at 1.17.10 due to an incompatibility in kustomize. If it's now working on 1.18.1 please let me know

**Comment by AlexsJones** [comment]
This needs us to update the Dockerfile

**Comment by beeme1mr** [comment]
Closing in favor of https://github.com/open-feature/open-feature-operator/issues/235
