### ISSUE TITLE
Consider restricting FlagSourceConfiguration CRD

### ISSUE THREAD

**Issue by Kavindu-Dodan** [open-feature/open-feature-operator#517]
Pre-requisites:

- [x] https://github.com/open-feature/open-feature-operator/issues/529
- [x] https://github.com/open-feature/flagd/issues/983
- [x] https://github.com/open-feature/open-feature-operator/issues/531

This issue was derived from comment https://github.com/open-feature/open-feature-operator/pull/514#issuecomment-1665877515 

OpenFeature operator supports configurability of flagd sidecar image & tag through two options,

- As startup arguments of the operator (using helm/K8s yaml) [^1]
- Using FlagSourceConfiguration's image & tag override options [^2]

The latter has a potential security impact as the side-car injection can be controlled based on the CRD definition of the respective deployment. 

**Solution**

For a given operator deployment, it is best to fix the sidecar image & tag and disallow any other overloading options. This means, keeping the Operator startup option and removing the option provided through `FlagSourceConfiguration` crd.

**Discussion**

Consider following when doing this,

- This is best done with beta version of the Operator API https://github.com/open-feature/open-feature-operator/issues/352 
- Consider migration path, warnings and test implementation impact 

[^1]: https://github.com/open-feature/open-feature-operator/blob/v0.2.35/main.go?rgh-link-date=2023-08-03T18%3A11%3A45Z#L93-L109
[^2]: https://github.com/open-feature/open-feature-operator/blob/v0.2.35/docs/flag_source_configuration.md#sidecar-configurations

**Comment by odubajDT** [comment]
The configurability of the flad sidecar via startup arguments (image & tag) is not part of the implementation yet and needs to be implemented separately. I would probably consider implementing this properly with tests after the implementation of v1beta1 is merged (but definitely before it's released, so we do not have breaking changes). WDYT @Kavindu-Dodan @toddbaert ?

**Comment by Kavindu-Dodan** [comment]
@odubajDT Actually this is already there but hidden inside a configuration loader [^1] and not well document 

Going forward we should only allow this configuration loading (+ document this behaviour) and disallow change through CRD 


[^1]: - https://github.com/open-feature/open-feature-operator/blob/v0.2.35/controllers/common/flagd-proxy.go#L68-L75

**Comment by odubajDT** [comment]
> @odubajDT Actually this is already there but hidden inside a configuration loader [1](#user-content-fn-1-51f87aad3da9155b04a47936f7360f75) and not well document
> 
> Going forward we should only allow this configuration loading (+ document this behaviour) and disallow change through CRD
> ## Footnotes
> 
>     1. * https://github.com/open-feature/open-feature-operator/blob/v0.2.35/controllers/common/flagd-proxy.go#L68-L75
>        
>        [↩](#user-content-fnref-1-51f87aad3da9155b04a47936f7360f75)

If I am correct, this is an image + tag for the flagd-proxy, but not for the flagd sidecar, I guess we want the same behavior here
