### ISSUE TITLE
Clean up leftover logic in `v1alpha*` APIs

### ISSUE THREAD

**Issue by odubajDT** [open-feature/open-feature-operator#532]
Pre-requisites:

- [x] https://github.com/open-feature/open-feature-operator/issues/529
- [x] https://github.com/open-feature/flagd/issues/983
- [x] https://github.com/open-feature/open-feature-operator/issues/531

## Goal

Clean up unused logic in api/* folder

### Details

After moving the code logic from using `v1alpha*` to `v1beta1` there will be a lot of dead code in api/v1alpha*/* files. This code can be removed. Please be aware that the definitions of the CRDs need to stay in place according to k8s standards.

### Acceptance criteria

- [x] conversion webhook logic is removed
- [x] struct functions are removed
- [x] tests are removed
- [x] CRDs are still in place

### DoD
- [x] acceptance criteria are met

**Comment by thisthat** [comment]
Looking at the [Kubernetes APIs](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/api), the API folder should only contain types and not code 🤔 while working on `v1beta1` I would avoid using code in the API package so moving to the stable version in the feature won't require any cleanup like this one

**Comment by odubajDT** [comment]
Agree, but what about potential conversion webhooks in the future? By default kubebuilder places them to the api/* folder..

**Comment by thisthat** [comment]
Good point 🤔 I won't mind having them still in the code - they can serve as documentation for going from alpha1 to alpha2 🤔 @toddbaert what would be your suggestion?

**Comment by toddbaert** [comment]
@thisthat:  @odubajDT said "potential conversion webhooks _**in the future"**_ but reading your comment, I think you're thinking about maintaining the old conversions (which I'd like not to do, I think).
