### ISSUE TITLE
Remove deprecated (and soon to be removed) --metrics-port usage from flagd-proxy startup.

### ISSUE THREAD

**Issue by toddbaert** [open-feature/open-feature-operator#586]
Remove [these instances](https://github.com/search?q=repo%3Aopen-feature%2Fopen-feature-operator+metrics-port&type=code) of deprecated `--metrics-port` and use `--management-port` instead.

See related flagd change.

:warning: this MUST be done before consuming the next release of flagd-proxy

**Comment by webstradev** [comment]
happy to pick this up

**Comment by toddbaert** [comment]
@webstradev assigned and thank you!
