### ISSUE TITLE
Add targeting validation

### ISSUE THREAD

**Issue by toddbaert** [open-feature/open-feature-operator#597]
With the addition of a [rigorous targeting schema](https://flagd.dev/schema/v0/targeting.json) for flagd, we can validate targeting rules. We should validate CRDs with these.

Tasks:

- [x] add JSON schema validation for RULES only (we don't need to validate entire flag configs, just rules)
  - [x] clear error messaging to admins when this validation fails
- [x] add option arg to disable validation in OFO (should be on by default)
- [x] associated tests

**Comment by toddbaert** [comment]
@odubajDT Are you still interested in working on this one?

**Comment by odubajDT** [comment]
Hi @toddbaert sorry for not tackling this already, have quite full backlog, but I can start working on it during this/next week. Would that be ok?

**Comment by odubajDT** [comment]
I am very sorry, but I currently do not have the capacity to handle this issue :/ Unassigning myself to not block this
