### ISSUE TITLE
FlagD interval field

### ISSUE THREAD

**Issue by udsprasad** [open-feature/open-feature-operator#617]
Hi Team,

we got a requirement where we need to modify the polling frequency from flagD to featureflag by using http provider. When we investigated in flagD documentation(https://flagd.dev/reference/sync-configuration/#source-configuration), we find the interval feild to modify the frequency as show in below screenshot.

<img width="1436" alt="image" src="https://github.com/open-feature/open-feature-operator/assets/64519099/9697fffa-cc76-45a4-9128-293f34e8a929">
 
does Openfeature operator supports interval field to configure the flagD? So, that I can configure the interval based on our requirement.

**Comment by Kavindu-Dodan** [comment]
@udsprasad thank you for bringing this up.

I checked the implementation and unfortunately we have not yet updated the Operator to support the `Interval` parameter [1].

The current default configuration is to use 5-second delay between http syncs.

[1] - https://github.com/open-feature/open-feature-operator/blob/apis/v0.2.39/apis/core/v1beta1/featureflagsource_types.go#L114-L141

**Comment by dabump** [comment]
@Kavindu-Dodan - I want to help adding it in. First is adding into the Source struct for API 
(https://github.com/open-feature/open-feature-operator/pull/619)

And then once API built / tagged, can add it into the injector mapping..seems simple? Not too sure of the building sequence, so hopefully i'm approaching this correctly

**Comment by Kavindu-Dodan** [comment]
@dabump great, thanks for the contribution 👍 

Yeah, the order is correct. First API change, release of the API and then you can release the Operator updated with the API.

**Comment by Kavindu-Dodan** [comment]
@dabump we released the new API with interval support - https://github.com/open-feature/open-feature-operator/releases/tag/apis%2Fv0.2.40

You should be able to continue with the next step of adding this to Operator.

**Comment by dabump** [comment]
Thank you @Kavindu-Dodan  - I've added the second PR to address the injector mapping. Hopefully all correctly done.

Here is the PR: https://github.com/open-feature/open-feature-operator/pull/621

Again, thanks for the awesome work you guys been doing!

**Comment by Kavindu-Dodan** [comment]
Fixed by https://github.com/open-feature/open-feature-operator/pull/621
