### ISSUE TITLE
[QUESTION/RESEARCH] How best to ensure a consistent/sane configuration between flagd and workloads

### ISSUE THREAD

**Issue by toddbaert** [open-feature/open-feature-operator#66]
Is there a way we can ensure than if flagD is running in a given pod, that the associated workload is configured consistently?

For example, if flagD is configured to be running on port 31310, is there a way to ensure the associated app in the same pod is connecting to flagD via the same port?

**Comment by beeme1mr** [comment]
@AlexsJones @thschue would either of you have any clever ideas for this? Perhaps the mutating webhook could set environment variables on the containers in the pod.

**Comment by AlexsJones** [comment]
I think the idea of SDK's always using a `FLAGD_PORT` env is probably the best choice here ( or at least having it as a fallback option if one isn't set )

**Comment by beeme1mr** [comment]
Created https://github.com/open-feature/flagd/issues/133 in flagD. Once we've agreed on the environment variable names, I'll create an issue in OFO to support setting them.

**Comment by beeme1mr** [comment]
Will be handled in https://github.com/open-feature/open-feature-operator/issues/63
