### ISSUE TITLE
[Helm] Improve custom namespace options

### ISSUE THREAD

**Issue by toddbaert** [open-feature/open-feature-operator#676]
The Helm chart allows the definition of a [custom default namespace](https://github.com/open-feature/open-feature-operator/blob/339e5c8cf49c54660ed3ee70fe988345b55de999/chart/open-feature-operator/README.md?plain=1#L98) where all OFO's resources will be created. Some improvements are needed here to support more use-cases.

We should:

- Add the ability to customize the namespace in use by OFO, _without actually creating it_.
- Add the ability to add additional labels and annotations to the created namespace.

**Comment by toddbaert** [comment]
@cpitstick-latai

**Comment by 7h3-3mp7y-m4n** [comment]
Hey I would like to take this issue 
/assign

**Comment by toddbaert** [comment]
OK @7h3-3mp7y-m4n ! Keep us up to date with your progress.

**Comment by 7h3-3mp7y-m4n** [comment]
thank you, I'll keep you updated on Slack
