### ISSUE TITLE
bug: Dependency incompatibility

### ISSUE THREAD

**Issue by james-milligan** [open-feature/open-feature-operator#92]
Recent changes to OFO dependencies seems to have caused an issue, docker image can no longer build.

Root cause seems to be the OFO go version currently set to 1.17, with packages needing to be updated to resolve vulnerabities. 

Steps to reproduce: 
```
git clone https://github.com/open-feature/open-feature-operator.git
cd open-feature-operator && make docker-build
```

expected output:
```
error: failed to solve: process "/bin/sh -c CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -a -o manager main.go" did not complete successfully: exit code: 2
make: *** [docker-build] Error 1
```

Resolution:
update the project to use go 1.19+, or downgrade the conflicting packages (may re-introduce vulnerabilities)

Further actions:
Introduce a git action to build the operator on pull requests to ensure the project can be built successfully before merge.

**Comment by james-milligan** [comment]
@AlexsJones @toddbaert @beeme1mr @skyerus

**Comment by beeme1mr** [comment]
I opened a PR to revert the dependency upgrade for now. I did spent a few minutes trying to find a version that would work but was unsuccessful. I've also created an issue for adding a GitHub action that validates PRs.
